### ISSUE TITLE
'isDefaultChangeDetectionStrategy' of undefined 

### ISSUE THREAD

**Issue by atorralb** [sanex3339/laravel-5-angular-2-example#4]
Hi,
do you know the reason what could be causing this?
![instantanea1](https://cloud.githubusercontent.com/assets/5326525/16697109/a34340e2-4537-11e6-86ea-643b9078c84e.png)

**Comment by sanex3339** [comment]
Hi, this is clear install?

**Comment by atorralb** [comment]
yes it is a fresh install
node version 6.2.1

![instantanea1](https://cloud.githubusercontent.com/assets/5326525/16708654/ea9e6242-45ea-11e6-9a38-90abeccef887.png)

**Comment by sanex3339** [comment]
what is your chrome version?

**Comment by atorralb** [comment]
It's 35.0
![instantanea2](https://cloud.githubusercontent.com/assets/5326525/16708822/505d9554-45ef-11e6-9aa4-150fed088101.png)

**Comment by sanex3339** [comment]
You must update your chrome to latest stable version

**Comment by atorralb** [comment]
oh shit it did worked
thank you for the tip
![instantanea3](https://cloud.githubusercontent.com/assets/5326525/16708972/bd6d6c0c-45f2-11e6-8794-4820daedc285.png)
