### ISSUE TITLE
this.socket = io('http://localhost:3000'); - showing error!

### ISSUE THREAD

**Issue by dev-deepu** [sanex3339/laravel-5-angular-2-example#5]
This line shows 'cannot find name io'. I tried to import socket.io-client like 'import * as io from "socket.io-client'. But it didnt work. So basically how do i use socket.io-client in this. Please help..

**Comment by sanex3339** [comment]
You have type definitions for socket.io-client?

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/cc3d223a946f661eff871787edeb0fcb8f0db156/socket.io-client
