### ISSUE TITLE
gulp command exception

### ISSUE THREAD

**Issue by rples** [sanex3339/laravel-5-angular-2-example#6]
Hi, `gulp `command throws exception like this below. How can I fix it? Thanks for your answer.

`C:\Users\r\Downloads\laravel-5-angular-2-example-master\node_modules\laravel
-elixir-webpack-official\node_modules\webpack\lib\Chunk.js:34
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
        ^
Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.Object.defineProperty.get (C:\Users\r\Downloads\laravel-5-angul
ar-2-example-master\node_modules\laravel-elixir-webpack-official\node_modules\we
bpack\lib\Chunk.js:34:9)
    at Compilation.processCommonChunk (C:\Users\r\Downloads\laravel-5-angula
r-2-example-master\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:82:21
)
    at Array.forEach (native)
    at Compilation.<anonymous> (C:\Users\r\Downloads\laravel-5-angular-2-exa
mple-master\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:67:17)
    at Compilation.applyPluginsBailResult (C:\Users\r\Downloads\laravel-5-an
gular-2-example-master\node_modules\laravel-elixir-webpack-official\node_modules
\tapable\lib\Tapable.js:52:27)
    at Compilation.seal (C:\Users\r\Downloads\laravel-5-angular-2-example-ma
ster\node_modules\laravel-elixir-webpack-official\node_modules\webpack\lib\Compi
lation.js:541:8)
    at Compiler.<anonymous> (C:\Users\r\Downloads\laravel-5-angular-2-exampl
e-master\node_modules\laravel-elixir-webpack-official\node_modules\webpack\lib\C
ompiler.js:436:15)
    at C:\Users\r\Downloads\laravel-5-angular-2-example-master\node_modules\
laravel-elixir-webpack-official\node_modules\tapable\lib\Tapable.js:152:11
    at Compilation.<anonymous> (C:\Users\r\Downloads\laravel-5-angular-2-exa
mple-master\node_modules\laravel-elixir-webpack-official\node_modules\webpack\li
b\Compilation.js:438:10)
    at C:\Users\r\Downloads\laravel-5-angular-2-example-master\node_modules\
laravel-elixir-webpack-official\node_modules\webpack\lib\Compilation.js:414:12`

**Comment by sanex3339** [comment]
Fixed in https://github.com/sanex3339/laravel-5-angular-2-example/commit/f935057fc2333f68d028f5a42bd3f911055b8f51

Remove `node_modules` folder and run `npm install`
