### ISSUE TITLE
Gulp watch

### ISSUE THREAD

**Issue by dariusll** [sanex3339/laravel-5-angular-2-example#8]
Using laravel homestead vm.

"gulp-watch" command not found

"gulp watch" starts watching, but can't detect any changes in resources/assets/typescript/.  Some times detects changes when nothing was changed.

**Comment by sanex3339** [comment]
`gulp-watch` 
Oops, readme mistyping.

**Comment by dariusll** [comment]
Working only when gulp watches localy. Not in homestead VM.

My opinion, issue can be closed, but note should be added to readme, that "gulp watch" have to be called not from homestead VM.

**Comment by sanex3339** [comment]
https://github.com/sanex3339/laravel-5-angular-2-example/commit/5972252e7ad51db5a9bfcc94e4ac24d0e6250e5f
